### ISSUE TITLE
Can't properly package for Gentoo

### ISSUE THREAD

**Issue by KireinaHoro** [cosven/april#1]
Simply writing an ebuild (attached) (which does the compile with `/usr/bin/python3.4 setup.py build`) results in a sandbox violation error (error log attached). Basically this is caused by the script trying to modify the system outside the build environment. Any help welcomed.

`april-0.0.1_alpha4.ebuild`:

```bash
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

PYTHON_COMPAT=( python3_4 )
DISTUTILS_SINGLE_IMPL=1
inherit distutils-r1

DESCRIPTION="Simplified data deserialization"
HOMEPAGE="https://github.com/cosven/april"

MY_PV="0.0.1a4"
SRC_URI="https://files.pythonhosted.org/packages/source/a/${PN}/${PN}-${MY_PV}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~x86"
IUSE=""

S=${WORKDIR}/${PN}-${MY_PV}

DEPEND=""
RDEPEND="${DEPEND}"
```

build log:

```
>>> Creating Manifest for /usr/local/portage/dev-python/april
 * april-0.0.1a4.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...             [ ok ]
 * checking ebuild checksums ;-) ...                                     [ ok ]
>>> Unpacking source...
>>> Unpacking april-0.0.1a4.tar.gz to /var/tmp/portage/dev-python/april-0.0.1_alpha4/work
>>> Source unpacked in /var/tmp/portage/dev-python/april-0.0.1_alpha4/work
>>> Preparing source in /var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4 ...
/usr/bin/python3.4 setup.py build
Traceback (most recent call last):
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.4/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/build_py.py", line 49, in run
    self.build_modules()
  File "/usr/lib/python3.4/distutils/command/build_py.py", line 352, in build_modules
    self.build_module(module, module_file, package)
  File "/usr/lib/python3.4/site-packages/setuptools/command/build_py.py", line 75, in build_module
    package)
  File "/usr/lib/python3.4/distutils/command/build_py.py", line 343, in build_module
    return self.copy_file(module_file, outfile, preserve_mode=0)
  File "/usr/lib/python3.4/distutils/cmd.py", line 348, in copy_file
    dry_run=self.dry_run)
  File "/usr/lib/python3.4/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/lib/python3.4/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 420, in _open
    self._violation("open", path, mode, *args, **kw)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 409, in _violation
    raise SandboxViolation(operation, args, kw)
setuptools.sandbox.SandboxViolation: SandboxViolation: open('/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4_python3.4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/tmp/portage/dev-python/april-0.0.1_alpha4/temp/easy_install-8_e0lnrq/pytest-runner-2.11.1/setup.py", line 49, in <module>
  File "/usr/lib/python3.4/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: SandboxViolation: open('/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4_python3.4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3.4/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/tmp/portage/dev-python/april-0.0.1_alpha4/temp/easy_install-8_e0lnrq/pytest-runner-2.11.1/setup.py", line 49, in <module>
  File "/usr/lib/python3.4/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: SandboxViolation: open('/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4_python3.4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    'console_scripts': []
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 317, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: open('/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4_python3.4/lib/ptr.py', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
 * ERROR: dev-python/april-0.0.1_alpha4::localrepo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_compile
 *   environment, line 2303:  Called distutils-r1_src_compile
 *   environment, line  694:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  282:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line  685:  Called distutils-r1_python_compile
 *   environment, line  560:  Called esetup.py 'build'
 *   environment, line  940:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/april-0.0.1_alpha4::localrepo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/april-0.0.1_alpha4::localrepo'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/april-0.0.1_alpha4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/april-0.0.1_alpha4/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4'
 * S: '/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4'
 * Messages for package dev-python/april-0.0.1_alpha4:
 * ERROR: dev-python/april-0.0.1_alpha4::localrepo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_compile
 *   environment, line 2303:  Called distutils-r1_src_compile
 *   environment, line  694:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  282:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line  685:  Called distutils-r1_python_compile
 *   environment, line  560:  Called esetup.py 'build'
 *   environment, line  940:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/april-0.0.1_alpha4::localrepo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/april-0.0.1_alpha4::localrepo'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/april-0.0.1_alpha4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/april-0.0.1_alpha4/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4'
 * S: '/var/tmp/portage/dev-python/april-0.0.1_alpha4/work/april-0.0.1a4'
```

**Comment by KireinaHoro** [comment]
Uh, it's my bad to leave out a dependency,
